name: instagram
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flutter_bloc: ^2.0.0
  equatable: ^0.6.1
  page_view_indicator: ^2.0.4
  image_picker: ^0.6.3+4

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

  assets:
    - assets/images/